### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by alezzz111** [Blobby-Boi/BlobbypassLEGO#1]
I DONT HAVE AN ISSUE, I JUST WANTED TO SAY THAT I INSTALLED WEGO LEGO YESTERDAY JUST TRYING TO FIND STUFF THAT COULD DEPLOY BLOBBY PASS AND I COULD NOT GET IT AND THERES NO WAY YOU JUST POSTED THIS FOR THIS EXACT APP BRO. Anyway , i just thought it was a crazy coincidence. Thanks for making this after spark vue got deleted off the webstore!!!

**Comment by Blobby-Boi** [comment]
:)
