### ISSUE TITLE
lego wedo doesnt load up with wifi on

### ISSUE THREAD

**Issue by 25HoursaDay** [Blobby-Boi/BlobbypassLEGO#2]

**Comment by theroadblock** [comment]
if what you mean is that it doesn't seem to load the website in the project after following the steps then yea i had this problem too

its as simple as clicking the pencil, green document, and pasting in the string with wifi on
then, itll actually load

if you close out of the program, you'll have to have the string in your clipboard to paste it in each time; its only (slightly) annoying

**Comment by 25HoursaDay** [comment]
I see
